spring:
  redis:
    database: 0
    host: ${redis-host}
    port: 7788
    password:
    timeout: 50000ms
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    cache:
      #自定义属性，redis缓存失效时间
      timeout-seconds: 1800